/* DO NOT EDIT!
   This file was automatically generated by m68k-palmos-stubgen v1.2
   from ssl-md.def  */

struct LibRef;
static struct LibRef *libref = 0;

extern void GLibClose(struct LibRef *);

#if __GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
/* Recent versions of prc-tools's GCC use %a4 or %a5 depending on -mown-gp.  */
    #ifdef __OWNGP__
    #define A4_GLOBALS
    #else
    #undef A4_GLOBALS
    #endif
#else
/* The prc-tools 0.5.0 version always uses %a4.  */
#define A4_GLOBALS
#endif

void GLib_CrMD(void)
{
    asm volatile ("
	.global MD2
MD2:
	move.l	#1,%%d0
	braw	dispatch
	.global MD2_Final
MD2_Final:
	move.l	#2,%%d0
	braw	dispatch
	.global MD2_Init
MD2_Init:
	move.l	#3,%%d0
	braw	dispatch
	.global MD2_Update
MD2_Update:
	move.l	#4,%%d0
	braw	dispatch
	.global MD2_options
MD2_options:
	move.l	#5,%%d0
	braw	dispatch
	.global MD5
MD5:
	move.l	#6,%%d0
	braw	dispatch
	.global MD5_Final
MD5_Final:
	move.l	#7,%%d0
	braw	dispatch
	.global MD5_Init
MD5_Init:
	move.l	#8,%%d0
	braw	dispatch
	.global MD5_Update
MD5_Update:
	move.l	#9,%%d0
	braw	dispatch

libname:
    .asciz \"MD Library\"
    .even

dispatch:
    lea libname(%%pc),%%a1
    move.l %%a1,%%d2
    "::);

#ifdef A4_GLOBALS
    asm volatile ("
    move.l %%a4,%%d1
    move.l %%d1,%%d1
    jbeq noglobals
    lea libref(%%a4),%%a1
noglobals:
    "::);
#else
    asm volatile ("
    lea libref@END(%%a5),%%a1
    "::);
#endif

    asm volatile ("
    move.l %0,%%d1
    braw GLibDispatch
    " : : "i" ('CrMD') );
}

#ifdef A4_GLOBALS

/* The 0.5.0 distribution didn't use a .dtors section.  In order to
   be usable with that compiler, we use a .ehook function and check
   for globals ourselves.  */

register void *reg_a4 asm("%a4");

void GLib_CrMD_clean(unsigned short cmd, void *PBP, unsigned short flags)
{
    if (reg_a4 && libref) {
	GLibClose(libref);
	libref = 0;
    }
}

asm("
.section ehook
.long GLib_CrMD_clean
");

#else

static void GLib_CrMD_clean() __attribute__ ((destructor, unused));

static void GLib_CrMD_clean()
{
    if (libref) {
	GLibClose(libref);
	libref = 0;
    }
}

#endif
